# requires environment variables:
# GOOGLE_COMPUTE_ZONE
# GOOGLE_PROJECT
# GCLOUD_SERVICE_KEY
# PROJECT_NAME - repo name (or hierarchical name)
version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      # prepare environment for building docker image
      - setup_remote_docker
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PROJECT_ID=gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}' >> $BASH_ENV
      # authorize gcloud
      - run:
          name: Authenticate to Google Cloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth configure-docker
      # deploy the image
      - run:
          name: Build, Tag, and Push Docker Image
          command: ./docker_build_tag.sh $PROJECT_ID $CIRCLE_BRANCH
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
